import zombie from "./Enemies/Zombie-with-pause-4fps.gif";
import spider from "./Enemies/Spider-with-pause-4fps.gif";
import hellHound from "./Enemies/Hell-Hound-with-pause-4fps.gif";
import thief from "./Enemies/Thief-with-pause-4fps.gif";
import elderSpider from "./Enemies/Elder-Spider-with-pause-4fps.gif";
import draugr from "./Enemies/Draugr-with-pause-4fps.gif";
import zombieShaman from "./Enemies/Zombie-Shaman-with-pause-4fps.gif";
import brigand from "./Enemies/Brigand-with-pause-4fps.gif";
import garmr from "./Enemies/Garmr-with-pause-4fps.gif";
import phantom from "./Enemies/Phantom-with-pause-4fps.gif";
import skeleton from "./Enemies/Skeleton-with-pause-4fps.gif";
import wight from "./Enemies/Wight-with-pause-4fps.gif";
import necromancer from "./Enemies/Necromancer-with-pause-4fps-192x192.gif";
export const Zombie = zombie;
export const Spider = spider;
export const HellHound = hellHound;
export const Thief = thief;
export const ElderSpider = elderSpider;
export const Draugr = draugr;
export const ZombieShaman = zombieShaman;
export const Brigand = brigand;
export const Garmr = garmr;
export const Phantom = phantom;
export const Skeleton = skeleton;
export const Wight = wight;
export const Necromancer = necromancer;

import knight from "./Player/Knight-with-pause-4fps.gif";
export const Knight = knight;
