export const FloorInfoArray = [
  "combat",
  "combat",
  "combat",
  "combat",
  "shop",
  "combat",
  "combat",
  "combat",
  "combat",
  "shop",
  "combat",
  "combat",
  "combat",
  "combat-shop",
  "boss",
];

export const StartingCharacterStats = {
  type: "Human",
  hp: 30,
  maxHp: 30,
  gold: 50,
  hasRevived: false,
  isFloorCompleted: false,
};

export const StartingItems = [
  {
    name: "Dull Sword",
    type: "Weapon",
    element: "Normal",
    damage: 2,
    class: "dull-sword",
  },
  {
    name: "Noble's Sword",
    type: "Weapon",
    element: "Normal",
    damage: 4,
    class: "nobles-sword",
    shop: "nobles-sword-shop",
    cost: 35,
  },
  {
    name: "Radiant Sword",
    type: "Weapon",
    element: "Holy",
    damage: 3,
    strong: "undead",
    class: "radiant-sword",
    shop: "radiant-sword-shop",
    cost: 50,
  },
  {
    name: "Flame-Kissed Sword",
    type: "Weapon",
    element: "Fire",
    damage: 3,
    strong: "beast",
    class: "flame-kissed-sword",
    shop: "flame-kissed-sword-shop",
    cost: 50,
  },
  {
    name: "Revival Pendant",
    type: "Accessory",
    element: "Holy",
    effect: "Upon death, revive and recover 30% HP",
    durability: 1,
    class: "revival-pendant",
    shop: "revival-pendant-shop",
    cost: 80,
  },
];

export const StartingEquipment = [
  {
    name: "Dull Sword",
    type: "Weapon",
    element: "Normal",
    damage: 2,
    class: "dull-sword",
  },
  {},
];

export const StartingShopInventory = [
  {
    name: "Noble's Sword",
    type: "Weapon",
    element: "Normal",
    damage: 4,
    class: "nobles-sword",
    shop: "nobles-sword-shop",
    cost: 35,
  },
  {
    name: "Radiant Sword",
    type: "Weapon",
    element: "Holy",
    damage: 3,
    strong: "undead",
    class: "radiant-sword",
    shop: "radiant-sword-shop",
    cost: 50,
  },
  {
    name: "Flame-Kissed Sword",
    type: "Weapon",
    element: "Fire",
    damage: 3,
    strong: "beast",
    class: "flame-kissed-sword",
    shop: "flame-kissed-sword-shop",
    cost: 50,
  },
  {
    name: "Revival Pendant",
    type: "Accessory",
    element: "Holy",
    effect: "Upon death, revive and recover 30% HP",
    durability: 1,
    class: "revival-pendant",
    shop: "revival-pendant-shop",
    cost: 80,
  },
];

export const EnemiesList = [
  {
    maxFloor: 4,
    name: "Zombie",
    type: "Undead",
    weakness: "Holy",
    hp: 4,
    damage: 1,
    speed: 2,
    gold: 5,
    class: "zombie",
    combatStyle: "attacker",
  },
  {
    maxFloor: 4,
    name: "Spider",
    type: "Beast",
    weakness: "Fire",
    hp: 2,
    damage: 1,
    speed: 4,
    skill: "Poison",
    gold: 5,
    class: "spider",
    combatStyle: "attacker",
  },
  {
    maxFloor: 9,
    name: "Draugr",
    type: "Undead",
    weakness: "Holy",
    hp: 6,
    damage: 1,
    speed: 2,
    skill: "Draw-Attacks",
    gold: 8,
    class: "draugr",
    combatStyle: "tank",
  },
  {
    maxFloor: 9,
    name: "Elder Spider",
    type: "Beast",
    weakness: "Fire",
    hp: 4,
    damage: 2,
    speed: 4,
    skill: "Poison",
    gold: 8,
    class: "elder-spider",
    combatStyle: "attacker",
  },
  {
    maxFloor: 9,
    name: "Zombie Shaman",
    type: "Undead",
    weakness: "Holy",
    hp: 3,
    damage: 1,
    speed: 1,
    heal: 2,
    buff: 1,
    gold: 8,
    class: "zombie-shaman",
    combatStyle: "support",
  },
];

export const EncounterAmounts = [2, 3];

export const EnemyPositions = ["first", "second", "third"];
