export const FloorInfoArray = [
  "combat",
  "combat",
  "combat",
  "combat",
  "shop",
  "combat",
  "combat",
  "combat",
  "combat",
  "shop",
  "combat",
  "combat",
  "combat",
  "combat-shop",
  "boss",
];

export const StartingCharacterStats = {
  type: "Human",
  hp: 30,
  maxHp: 30,
  gold: 50,
  hasRevived: false,
  isFloorCompleted: false,
};

export const StartingStatTotals = {
  totalGold: 50,
  totalKills: 0,
};

export const StartingItems = [
  {
    name: "Dull Sword",
    type: "Weapon",
    element: "Normal",
    damage: 2,
    class: "dull-sword",
  },
];

export const StartingEquipment = [
  {
    name: "Dull Sword",
    type: "Weapon",
    element: "Normal",
    damage: 2,
    class: "dull-sword",
  },
  {},
];

export const StartingShopInventory = [
  {
    name: "Noble's Sword",
    type: "Weapon",
    element: "Normal",
    damage: 4,
    class: "nobles-sword",
    shop: "nobles-sword-shop",
    cost: 35,
  },
  {
    name: "Radiant Sword",
    type: "Weapon",
    element: "Holy",
    damage: 3,
    strong: "undead",
    class: "radiant-sword",
    shop: "radiant-sword-shop",
    cost: 50,
  },
  {
    name: "Flame-Kissed Sword",
    type: "Weapon",
    element: "Fire",
    damage: 3,
    strong: "beast",
    class: "flame-kissed-sword",
    shop: "flame-kissed-sword-shop",
    cost: 50,
  },
  {
    name: "Revival Pendant",
    type: "Accessory",
    element: "Holy",
    effect: "Upon death, revive and recover 30% HP",
    durability: 1,
    class: "revival-pendant",
    shop: "revival-pendant-shop",
    cost: 80,
  },
];

export const EnemiesList = [
  {
    floors: "early",
    name: "Zombie",
    type: "Undead",
    weakness: "Holy",
    hp: 4,
    damage: 1,
    speed: 2,
    gold: 5,
    class: "zombie",
    combatStyle: "attacker",
  },
  {
    floors: "early",
    name: "Spider",
    type: "Beast",
    weakness: "Fire",
    hp: 2,
    damage: 1,
    speed: 4,
    skill: "Poison",
    gold: 5,
    class: "spider",
    combatStyle: "attacker",
  },
  {
    floors: "early",
    name: "Hell Hound",
    type: "Beast",
    weakness: "Fire",
    hp: 2,
    damage: 2,
    speed: 6,
    gold: 5,
    class: "hell-hound",
    combatStyle: "attacker",
  },
  {
    floors: "early-mid",
    name: "Thief",
    type: "Human",
    weakness: "Electric",
    hp: 2,
    damage: 1,
    speed: 5,
    skill: "Bleed",
    gold: 8,
    class: "thief",
    combatStyle: "attacker",
  },
  {
    floors: "mid",
    name: "Draugr",
    type: "Undead",
    weakness: "Holy",
    hp: 6,
    damage: 1,
    speed: 2,
    skill: "Draw-Attacks",
    gold: 8,
    class: "draugr",
    combatStyle: "tank",
  },
  {
    floors: "mid",
    name: "Elder Spider",
    type: "Beast",
    weakness: "Fire",
    hp: 4,
    damage: 2,
    speed: 4,
    skill: "Poison",
    gold: 8,
    class: "elder-spider",
    combatStyle: "attacker",
  },
  {
    floors: "mid-late",
    name: "Zombie Shaman",
    type: "Undead",
    weakness: "Holy",
    hp: 3,
    damage: 1,
    speed: 1,
    heal: 2,
    buff: 1,
    gold: 8,
    class: "zombie-shaman",
    combatStyle: "support",
  },
  {
    floors: "mid-late",
    name: "Brigand",
    type: "Human",
    weakness: "Electric",
    hp: 4,
    damage: 3,
    speed: 3,
    gold: 10,
    class: "brigand",
    combatStyle: "attacker",
  },
  {
    floors: "late",
    name: "Phantom",
    type: "Undead",
    weakness: "Holy",
    hp: 6,
    damage: 2,
    speed: 5,
    skill: "Bleed",
    gold: 10,
    class: "phantom",
    combatStyle: "attacker",
  },
  {
    floors: "late",
    name: "Garmr",
    type: "Beast",
    weakness: "Fire",
    hp: 6,
    damage: 4,
    speed: 6,
    gold: 10,
    class: "garmr",
    combatStyle: "attacker",
  },
];

export const EncounterAmounts = [2, 3];

export const EnemyPositions = ["first", "second", "third"];

export const BossEnemiesList = [
  [
    {
      name: "Wight",
      type: "Undead",
      weakness: "Holy",
      hp: 6,
      damage: 2,
      speed: 3,
      skill: "Draw-Attacks",
      gold: 15,
      class: "wight",
      combatStyle: "tank",
    },
    {
      name: "Necromancer",
      type: "Undead",
      weakness: "Holy",
      hp: 50,
      damage: 2,
      speed: 2,
      skill: "Raise-Undead",
      skill2: "Poison",
      buff: 2,
      gold: 100,
      class: "necromancer",
      combatStyle: "boss",
    },
    {
      name: "Skeleton",
      type: "Undead",
      weakness: "Holy",
      hp: 4,
      damage: 3,
      speed: 4,
      skill: "Bleed",
      gold: 15,
      class: "skeleton",
      combatStyle: "attacker",
    },
  ],
];
